alpaca-finance/xALPACA-contract

contracts/8.7/xALPACA.sol, tests/GrassHouse.test.ts, tests/xALPACA.test.ts
Change the maximum lock time from 4 years to 1 year
This would be more suitable for ALPACA holder
- MAX_LOCK constant variable in xAlpaca contract
- MAX_LOCK constant variable in test scripts
=> [main][feat] change MAX_LOCK from 4 to 1 year

package.json, tsconfig.cjs.json
=> [main][feat]: publish package on npm script

contracts/8.7/xALPACA.sol
Since Solidity > 0.8.0 integrate SafeMath functionality to the compiler, we can remove the lib from xAlpaca contract
https://docs.soliditylang.org/en/v0.8.10/080-breaking-changes.html
Save Gas Cost
- replace .sub.() to -
- replace .mul() to *
- replace .add() to +
=> [main][fix] Remove SafeMath

contracts/8.7/xALPACA.sol, tests/unit/GrassHouse.test.ts, tests/unit/xALPACA.test.ts
Raise the MAX_LOCK value to <53 weeks
So that user can be able to lock at the maximum of 52 weeks
- Change MAX_LOCK constant to 53 weeks - 1 in seconds
=> [main][feat] Change MAX_LOCK to less than 53 weeks

contracts/8.7/GrassHouse.sol, contracts/8.7/utils/Math128.sol
- add math128 utils
- fix grasshouse _claim function find max balance before cast type
=> [main][fix] grasshouse _claim function

contracts/8.7/ProxyToken.sol
Clean up Proxy Token. Add missing variable visibility and remove comment.
=> [main][chore] Clean Proxy Token

.mainnet.json, .openzeppelin/unknown-56.json, .openzeppelin/unknown-97.json, .solhint.json, .testnet.json, deploy/entities/config.ts, deploy/exec/alpaca-feeder/deploy/alpaca-feeder.ts, deploy/exec/grasshouse/deploy/grasshouse.ts, package.json
Deploy xALPACA to testnet + mainnet preparation
=> [main][deploy] Deploy xALPACA to testnet + mainnet preparation

.mainnet.json, .openzeppelin/unknown-56.json, deploy/exec/alpaca-feeder/deploy/alpaca-feeder.ts, deploy/exec/grasshouse/deploy/grasshouse.ts
Deploy xALPACA, ALPACA GrassHouse, and THG GrassHouse to mainnet.
=> [main][deploy] xALPACA, ALPACA GrassHouse, and THG GrassHouse to mainnet

contracts/8.10/ScientixFeeder.sol, contracts/8.10/interfaces/IStakingPool.sol, contracts/8.10/mocks/MockStakingPool.sol, deploy/exec/scientix-feeder/deploy/scientix-feeder.ts, package.json, tests/unit/ScientixFeeder.test.ts
Add new feeder for Scientix Staking Pool
Migrate from old GR to xAlpaca Grasshouse
bb11c628a42df383341c30b35495d47ef6c678f8 chore: add yarn command for deploy scix feeder
90b974a979a6915e04925f3621f2291f21a3707c chore: add scientix feeder deploy scipt
08e46cae323ae3586a235c25238eeb074f7f5698 fix: remove IVault interface as it's not one.
0bfbc53ecd30c5cc2aadb9941dd9f0e2b443d99a fix: rename alpaca to scix in test script
44964a304d8065ecd50141018b5cb708245eb176 feat: add scientix feeder
=> [main][feat] Add Scientix feeder

contracts/8.10/GrassHouse.sol, deploy/exec/grasshouse/upgrade/grasshouse.ts, hardhat.config.forking.ts, package.json, tests/fork-tests/UpgradeGrassHouseWhitelistedCallers.test.ts, tests/integration/UpgradeGrassHouseWhitelistedCallers.test.ts, tests/unit/GrassHouse.test.ts
- allow whitelistedCheckpointCallers to call checkpoint token
=> [main][feat] whitelisted callers to call checkpointToken

.mainnet.json, .openzeppelin/unknown-56.json, deploy/exec/grasshouse/deploy/grasshouse.ts, deploy/exec/grasshouse/upgrade/grasshouse.ts, hardhat.config.forking.ts
=> [main][deploy] LAND Grass House

.mainnet.json, .openzeppelin/unknown-56.json, deploy/exec/grasshouse/deploy/grasshouse.ts
=> [main][deploy] HIGH and DLTA Graze

package.json
- Update npm version for new scientix feeder
=> [main][publish] update npm version.

contracts/8.10/TaxFeeder.sol, contracts/8.10/interfaces/IAnyswapV4Router.sol, contracts/8.10/mocks/MockAnySwapV4Router.sol, package.json, tests/unit/TaxFeeder.test.ts
=> [main][feat] tax feeder

contracts/8.10/SafeToken.sol
Add check if the callee is a contract in SafeToken Lib
Security purpose
=> [main][fix] Contract check in SafeToken lib

contracts/8.10/Tribute.sol, contracts/8.10/tribute/RootStorage.sol, contracts/8.10/tribute/Tribute.sol, package.json, tests/helpers/time.ts, tests/unit/Tribute.test.ts, utils/format.ts, utils/merkle/balance-tree.ts, utils/merkle/merkle-tree.ts, utils/merkle/parse-balance-map.ts
Add Tribute contract
So BSC xALPACA holder are eligible for FTM GR
=> [main][feat] Add Tribute contract for distributing FTM GR -> BSC holders

package.json
- publish npm version 0.0.6 for tributes and rootstorage contracts
=> [main][chore] publish npm version 0.0.6

deploy/exec/tribute/deploy/tribute.ts
- add set whitelist keeper to tribute deployment script
=> [main][fix] tribute deployment script

contracts/8.10/interfaces/IAnyswapV4Router.sol, contracts/8.10/mocks/MockAnySwapV4Router.sol, contracts/8.10/mocks/MockFairLaunch.sol, contracts/8.10/mocks/MockGrassHouse.sol, contracts/8.10/mocks/MockStakingPool.sol
Make compiling contracts results with 0 warnings
Clean up the codebase
=> [main][chore] Silence warning during compilation

.mainnet.json, .openzeppelin/unknown-56.json, deploy/exec/grasshouse/deploy/grasshouse.ts
=> [main][deploy] XWG and DEP GrassHouse

.fantom_mainnet.json, .openzeppelin/unknown-250.json, deploy/exec/alpaca-feeder/deploy/alpaca-feeder02.ts, deploy/exec/grasshouse/deploy/grasshouse.ts, deploy/exec/proxy-token/deploy/proxy-token.ts, hardhat.config.ftm.forking.ts, hardhat.config.ts, package.json, utils/deployer-helper.ts
- Deploy xALPACA to Fantom
- ALPACA holders on Fantom can participate in governance and earn revenue sharing on ALPACA
=> [main][deploy] xALPACA to Fantom

.mainnet.json, .openzeppelin/unknown-56.json, deploy/exec/grasshouse/deploy/grasshouse.ts
=> [main][deploy] BSW GR

.mainnet.json, .openzeppelin/unknown-56.json, deploy/exec/grasshouse/deploy/grasshouse.ts
=> [main][deploy] TINC Grass House

.mainnet.json, .openzeppelin/unknown-56.json, deploy/exec/grasshouse/deploy/grasshouse.ts
=> [main][deploy] GYMNET GrassHouse

contracts/8.10/xALPACA.sol, hardhat.config.ts, tests/unit/xALPACA.test.ts
- allow multisig contract to lock in xalpaca ( createlock, extend time, extend amount)
-xAlpaca
-xAlpaca.test.ts
=> [main][feat]: support multisig to lock in xalpaca

contracts/8.10/xALPACA.sol, hardhat.config.ts, tests/unit/xALPACA.test.ts
- add redistributors whitelisted
- redistribute can be called by Redistributors only
=> [main][feat]: redistributors whitelisted

package.json
- publish package for using at fe
=> [main][chore]: publish package

.openzeppelin/unknown-250.json, .openzeppelin/unknown-56.json, contracts/8.10/xALPACA.sol, deploy/exec/xalpaca/upgrade/xalpaca.ts
=> [main][deploy] Upgrade xALPACA to support early withdraw

.mainnet.json, .openzeppelin/unknown-56.json, deploy/exec/grasshouse/deploy/grasshouse.ts
=> [main][deploy] PSR GrassHouse

.mainnet.json, .openzeppelin/unknown-56.json, contracts/8.10/xALPACA.sol, deploy/exec/grasshouse/deploy/grasshouse.ts, tests/unit/xALPACA.test.ts
=> deploy: pSTAKE grasshouse

contracts/8.19/miniFL/Rewarder.sol, contracts/8.19/miniFL/interfaces/IMiniFL.sol, contracts/8.19/miniFL/interfaces/IRewarder.sol, tests/forge/base/BaseTest.sol, tests/forge/miniFL/MiniFL_BaseTest.t.sol, tests/forge/miniFL/MiniFL_Harvest.t.sol, tests/forge/miniFL/MiniFL_HarvestWithRewarder.t.sol, tests/forge/miniFL/MiniFL_SetPoolRewarders.t.sol
Change the logic of rewarder to match with miniFL
=> [feat][feat] Rewarder feed with end timestamp

contracts/8.19/xALPACAv2.sol, contracts/8.19/xALPACAv2RevenueDistributor/xALPACAv2RevenueDistributor.sol, tests/forge/base/BaseTest.sol, tests/forge/xALPACAv2/xALPACAv2_CancelUnlock.t.sol
Integrate xALPACAv2 with RevenueDistributor
Gov Staker should get revenue distribution
=> [main][feat] Integrate xALPACAv2 with RevenueDistributor

contracts/8.19/xALPACAv2.sol, tests/forge/xALPACAv2/xALPACAv2_Transfer.t.sol
=> [main][feat] xALPACAv2 Transferable

contracts/8.19/xALPACAv2RevenueDistributor/xALPACAv2Rewarder.sol, tests/forge/xALPACAv2RevenueDistributor/xALPACAv2RevenueDistributor_Complex.t.sol
=> [main][fix] rewarder update pool

contracts/8.10/xALPACAMigrator.sol, package.json
=> [main][feat] xalpaca migrator redistribute

contracts/8.19/xALPACAv2RevenueDistributor/interfaces/IxALPACAv2RevenueDistributor.sol, contracts/8.19/xALPACAv2RevenueDistributor/interfaces/IxALPACAv2Rewarder.sol, contracts/8.19/xALPACAv2RevenueDistributor/xALPACAv2RevenueDistributor.sol, contracts/8.19/xALPACAv2RevenueDistributor/xALPACAv2Rewarder.sol, deploy/exec/xalpaca-v2-revenue-distributor/config/add-rewarder.ts, deploy/exec/xalpaca-v2-revenue-distributor/config/set-pool-rewarder.ts, deploy/exec/xalpaca-v2-rewarder/deploy/xalpaca-v2-rewarder.ts, package.json, tests/forge/base/xALPACAV2_BaseTest.sol, tests/forge/xALPACAv2RevenueDistributor/xALPACAv2RevenueDistributor_BaseTest.t.sol, tests/forge/xALPACAv2RevenueDistributor/xALPACAv2RevenueDistributor_HarvestWithRewarder.t.sol, tests/forge/xALPACAv2RevenueDistributor/xALPACAv2RevenueDistributor_SetPoolRewarders.t.sol
=> [main][fix] xALPACAv2Rewarder

contracts/8.19/xALPACAv2.sol, contracts/8.19/xALPACAv2RevenueDistributor/interfaces/IxALPACAv2RevenueDistributor.sol, deploy/exec/xalpaca-v2/deploy/xalpaca-v2.ts, tests/forge/base/BaseTest.sol, tests/forge/base/xALPACAV2_BaseTest.sol, tests/forge/xALPACAMigrator/xALPACAMigrator_BaseTest.t.sol, tests/forge/xALPACAv2/xALPACAv2_Redistribute.t.sol, tests/forge/xALPACAv2/xALPACAv2_WIthdraw.t.sol
=> [main][feat] xalpaca v2 redistribute

.openzeppelin/bsc.json, contracts/8.10/GrassHouse_DisabledFeed.sol, deploy/exec/grasshouse/upgrade/grasshouse.ts, utils/deployer-helper.ts
=> [main][feat] upgrade grasshouse

deploy/exec/xalpaca-v2/config/set-whitelisted-redistributor.ts, deploy/exec/xalpaca/config/withdraw-acc-redistribute.ts, deploy/exec/xalpaca/upgrade/xalpaca.ts, package.json
=> [main][chore] redistribute and withdrawAccFee script

contracts/8.19/xALPACAv2RevenueDistributor/xALPACAv2RevenueDistributor.sol, contracts/8.19/xALPACAv2RevenueDistributor/xALPACAv2Rewarder.sol, package.json
=> [main][chore] emit feed amount

.openzeppelin/bsc.json, contracts/8.10/GrassHouse.sol, deploy/exec/grasshouse/upgrade/grasshouse.ts, deploy/services/timelock/maybe-multisig/index.ts
=> [main][deploy] upgrade ALPACA grasshouse

.mainnet.json, contracts/8.19/xALPACAv2RevenueDistributor/xALPACAv2Rewarder.sol, deploy/exec/xalpaca-v2-revenue-distributor/config/set-whitelisted-feeder.ts, deploy/exec/xalpaca-v2-rewarder/config/feed-rewarder.ts, deploy/exec/xalpaca-v2-rewarder/deploy/xalpaca-v2-rewarder.ts, deploy/interfaces/config.ts, package.json
=> [main][feat] Pyth Rewarder

.openzeppelin/bsc.json, deploy/exec/alpaca-feeder/upgrade/alpaca-feeder.ts, deploy/exec/xalpaca-v2/upgrade/xalpaca-v2.ts
=> [main][deploy] Upgrade alpaca feeder

contracts/8.19/xALPACAv2RevenueDistributor/xALPACAv2Rewarder.sol, deploy/exec/xalpaca-v2-rewarder/config/force-set-reward-debt.ts, package.json
- Fix wrong calculation on user.rewardDebt
=> [main][fix] Fix harvesting from rewarder

contracts/8.19/xALPACAv2RevenueDistributor/xALPACAv2Rewarder.sol, deploy/exec/xalpaca-v2-rewarder/config/find-pending-tokens.ts, deploy/exec/xalpaca-v2-rewarder/config/force-set-reward-debt.ts, deploy/exec/xalpaca-v2-rewarder/upgrade/xalpaca-v2-rewarder.ts, package.json
=> [main][fix] Fix wrong reward debt calculation
